---
- name: Download elixir Release
  unarchive: src=https://github.com/elixir-lang/elixir/archive/v1.2.0.zip dest=/usr/local/ creates=/usr/local/elixir-1.2.0 copy=no mode=0755
  tags:
    - elixir-download-release

- name: Install elixir Release
  command: make clean test chdir=/usr/local/elixir-1.2.0 creates=/usr/local/elixir-1.2.0/lib/eex/ebin
  tags:
    - elixir-install

- name: Create elixir links
  action: file src=/usr/local/elixir-1.2.0/bin/{{ item }} dest=/usr/local/bin/{{ item }} state=link
  with_items:
    - elixir
    - elixirc
    - iex
    - mix
