---
- file: path=/opt state=directory

- name: Get JDK
  get_url: url=http://{{ manager_url}}/tgz/jdk-7u65-linux-x64.tar.gz dest=/opt/jdk-7u65-linux-x64.tar.gz

- name: Unpack JDK7
  action: command creates=/opt/jdk1.7.0_65 chdir=/opt tar zxvf /opt/jdk-7u65-linux-x64.tar.gz --owner=root
  register: jdk_installed

- file: src=/opt/jdk1.7.0_65 dest=/opt/jdk state=link force=yes

- name: Set java link
  action: command update-alternatives --install /usr/bin/java java /opt/jdk/bin/java 1
#  only_if: '${jdk_installed.changed}'

- name: Set jar link
  action: command update-alternatives --install /usr/bin/jar jar /opt/jdk/bin/jar 1
#  only_if: '${jdk_installed.changed}'

#- name: Remove JDK7 archive
#  file: path=/opt/jdk-7u65-linux-x64.tar.gz state=absent

- get_url: url=http://{{ manager_url }}/tgz/apache-ant-1.9.2-bin.tar.gz dest=/opt/apache-ant-1.9.2-bin.tar.gz

- name: Unpack Ant
  action: command creates=/opt/apache-ant-1.9.2 chdir=/opt tar zxvf /opt/apache-ant-1.9.2-bin.tar.gz --owner=root
  register: ant_installed

- file: src=/opt/apache-ant-1.9.2 dest=/opt/ant state=link force=yes

#- name: Remove Ant archive
#  file: path=/opt/apache-ant-1.9.2-bin.tar.gz state=absent

- get_url: url=http://{{ manager_url }}/tgz/apache-maven-3.2.1-bin.tar.gz dest=/opt/apache-maven-3.2.1-bin.tar.gz

- name: Unpack Maven
  action: command creates=/opt/apache-maven-3.2.1 chdir=/opt tar zxvf /opt/apache-maven-3.2.1-bin.tar.gz --owner=root
  register: maven_installed

- file: src=/opt/apache-maven-3.2.1 dest=/opt/maven state=link force=yes


